{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mylisabox.multicastlock",
    "module": "android_multicast_lock_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        }
      ],
      "files": [
        {
          "name": "android_multicast_lock_debug-1.0.aar",
          "url": "android_multicast_lock_debug-1.0.aar",
          "size": 5119,
          "sha512": "5533345e3828672fd3f85072d01bc5a076f9453181834f9aa0e5df494215623878c1f587e06ba63fd5123559609454037aec7b8b3226caa82ae81e6d2a744e2d",
          "sha256": "a3dc5e36d2da92e5068c27caa3d7b028144d40d29c1eecb98c3cce4dea70ccd1",
          "sha1": "2dd9fc89dd3817622b758682ba8eb811c859be02",
          "md5": "3f08d7e9e33ab56170a1c6665853ae0b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        }
      ],
      "files": [
        {
          "name": "android_multicast_lock_debug-1.0.aar",
          "url": "android_multicast_lock_debug-1.0.aar",
          "size": 5119,
          "sha512": "5533345e3828672fd3f85072d01bc5a076f9453181834f9aa0e5df494215623878c1f587e06ba63fd5123559609454037aec7b8b3226caa82ae81e6d2a744e2d",
          "sha256": "a3dc5e36d2da92e5068c27caa3d7b028144d40d29c1eecb98c3cce4dea70ccd1",
          "sha1": "2dd9fc89dd3817622b758682ba8eb811c859be02",
          "md5": "3f08d7e9e33ab56170a1c6665853ae0b"
        }
      ]
    }
  ]
}
