{
  "formatVersion": "1.1",
  "component": {
    "group": "com.audiofetch.af_disco_module",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "com.mylisabox.multicastlock",
          "module": "android_multicast_lock_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 17771293,
          "sha512": "ac7d5dd293c59759c01bb9ff7185108aaa48abdc5600798e0be0efada027f26ce68e8fd684d977b521bcf12fd3004f945ad8cb2447b270a938a41bb5adcb615a",
          "sha256": "e6beda34165e22e0e38eec8dd1a36c843645a8818ee7716366a7d2ce25b5715a",
          "sha1": "cfcf4c941e31da90d757d01be3df4d3c7fcdd098",
          "md5": "60e8c307484e6c3099b874099301a25b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "com.mylisabox.multicastlock",
          "module": "android_multicast_lock_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 17771293,
          "sha512": "ac7d5dd293c59759c01bb9ff7185108aaa48abdc5600798e0be0efada027f26ce68e8fd684d977b521bcf12fd3004f945ad8cb2447b270a938a41bb5adcb615a",
          "sha256": "e6beda34165e22e0e38eec8dd1a36c843645a8818ee7716366a7d2ce25b5715a",
          "sha1": "cfcf4c941e31da90d757d01be3df4d3c7fcdd098",
          "md5": "60e8c307484e6c3099b874099301a25b"
        }
      ]
    }
  ]
}
